### ISSUE TITLE
Docs: How to install and run locally

### ISSUE THREAD

**Issue by sirkitree** [MetaGenAI/MetaGenNeos#2]
Please document how we can install this and run it locally so as not to run into network slowness when recording.

**Comment by guillefix** [comment]
I've now added the instructions to install and run locally https://github.com/MetaGenAI/MetaGenNeos/blob/main/README.md . I'll wait till a couple of people test it before closing this

**Comment by guillefix** [comment]
The instructions have now been tested to work by a few people.
